title: Negev Environmental Health and Sustainability Institute
titleHE: המכון לקיימות, סביבה ובריאות בנגב

email: RuthieB@clalit.org.il

descriptionHE: > # this means to ignore newlines until "baseurl:"
  ת.ד. 151 באר שבע 84101 ישראל
description: > # this means to ignore newlines until "imgurl:"
  P.O.Box 151 Be'er Sheva, 84101 Israel.

imgurl: "http://vsevkayf.github.io/hasa/assets/images" # the subpath of your site, e.g. /blog/
cssurl: "http://vsevkayf.github.io/hasa/assets/css" # the subpath of your site, e.g. /blog/
jsurl: "http://vsevkayf.github.io/hasa/assets/js" # the subpath of your site, e.g. /blog/
baseurl: "" # the subpath of your site, e.g. /blog/
#siteurl: "http://nehsi.org" # the base hostname & protocol for your site
url: "http://vsevkayf.github.io/hasa/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
